"""Constants for Smart Climate Proxy."""

from __future__ import annotations

from homeassistant.const import Platform

DOMAIN = "smart_climate_proxy"
PLATFORMS: list[Platform] = [Platform.CLIMATE, Platform.NUMBER, Platform.SWITCH, Platform.SENSOR]

STORE_VERSION = 2
STORE_KEY = "smart_climate_proxy"

CONF_NAME = "name"
CONF_TARGET_CLIMATE = "target_climate"
CONF_TEMPERATURE_SENSOR = "temperature_sensor"
CONF_QUIET_SWITCH = "quiet_switch"

CONF_TARGET_TEMPERATURE = "target_temperature"
CONF_LOWER_TOLERANCE = "lower_tolerance"
CONF_UPPER_TOLERANCE = "upper_tolerance"
CONF_CORRECTION_INTERVAL_MINUTES = "correction_interval_minutes"
CONF_SETPOINT_STEP = "setpoint_step"
CONF_LEARNING_STABLE_HOURS = "learning_stable_hours"
CONF_MANUAL_OVERRIDE_MINUTES = "manual_override_minutes"
CONF_LEARNING_RESOLUTION = "learning_resolution"

CONF_APPLY_TO_DEVICE = "apply_to_device"
CONF_LEARNING_ENABLED = "learning_enabled"
CONF_MANUAL_OVERRIDE_ENABLED = "manual_override_enabled"
CONF_USE_CUSTOM_LIMITS = "use_custom_limits"
CONF_USE_QUIET_SWITCH = "use_quiet_switch"

CONF_FORWARD_HVAC_MODE = "forward_hvac_mode"
CONF_FORWARD_FAN_MODE = "forward_fan_mode"
CONF_FORWARD_SWING_MODE = "forward_swing_mode"
CONF_FORWARD_PRESET_MODE = "forward_preset_mode"

CONF_HEAT_MIN_SETPOINT = "heat_min_setpoint"
CONF_HEAT_MAX_SETPOINT = "heat_max_setpoint"
CONF_COOL_MIN_SETPOINT = "cool_min_setpoint"
CONF_COOL_MAX_SETPOINT = "cool_max_setpoint"

DEFAULTS = {
    CONF_TARGET_TEMPERATURE: 20.0,
    CONF_LOWER_TOLERANCE: 0.5,
    CONF_UPPER_TOLERANCE: 1.0,
    CONF_CORRECTION_INTERVAL_MINUTES: 30,
    CONF_SETPOINT_STEP: 1.0,
    CONF_LEARNING_STABLE_HOURS: 4.0,
    CONF_MANUAL_OVERRIDE_MINUTES: 60,
    CONF_LEARNING_RESOLUTION: 1.0,
    CONF_APPLY_TO_DEVICE: False,
    CONF_LEARNING_ENABLED: True,
    CONF_MANUAL_OVERRIDE_ENABLED: True,
    CONF_USE_CUSTOM_LIMITS: False,
    CONF_USE_QUIET_SWITCH: False,
    CONF_FORWARD_HVAC_MODE: True,
    CONF_FORWARD_FAN_MODE: True,
    CONF_FORWARD_SWING_MODE: True,
    CONF_FORWARD_PRESET_MODE: False,
    CONF_HEAT_MIN_SETPOINT: 8.0,
    CONF_HEAT_MAX_SETPOINT: 30.0,
    CONF_COOL_MIN_SETPOINT: 8.0,
    CONF_COOL_MAX_SETPOINT: 30.0,
}

NUMERIC_OPTIONS = {
    CONF_TARGET_TEMPERATURE,
    CONF_LOWER_TOLERANCE,
    CONF_UPPER_TOLERANCE,
    CONF_CORRECTION_INTERVAL_MINUTES,
    CONF_SETPOINT_STEP,
    CONF_LEARNING_STABLE_HOURS,
    CONF_MANUAL_OVERRIDE_MINUTES,
    CONF_LEARNING_RESOLUTION,
    CONF_HEAT_MIN_SETPOINT,
    CONF_HEAT_MAX_SETPOINT,
    CONF_COOL_MIN_SETPOINT,
    CONF_COOL_MAX_SETPOINT,
}

SWITCH_OPTIONS = {
    CONF_APPLY_TO_DEVICE,
    CONF_LEARNING_ENABLED,
    CONF_MANUAL_OVERRIDE_ENABLED,
    CONF_USE_CUSTOM_LIMITS,
    CONF_FORWARD_HVAC_MODE,
    CONF_FORWARD_FAN_MODE,
    CONF_FORWARD_SWING_MODE,
    CONF_FORWARD_PRESET_MODE,
    CONF_USE_QUIET_SWITCH,
}
